# Generated by Django 3.2.9 on 2021-12-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('local', models.CharField(blank=True, max_length=250, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('Affiché', 'Affiché'), ('Masqué', 'Masqué')], default='Affiché', max_length=250, null=True)),
                ('cssClass', models.CharField(blank=True, choices=[('blue', 'Bleu'), ('red', 'Rouge'), ('green', 'Vert'), ('black', 'black'), ('olive', 'olive'), ('blueviolet', 'blueviolet'), ('dimgray', 'dimgray'), ('orange', 'orange')], default='blue', max_length=50, null=True)),
                ('partner', models.ManyToManyField(blank=True, null=True, related_name='partners', to='partner.Partner')),
            ],
        ),
    ]
